# codemagic.yaml — MASTRO ERP Build Config
# Builda iOS + Android nel cloud senza Mac

workflows:
  mastro-ios:
    name: MASTRO ERP iOS
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      node: 18
      xcode: latest
      groups:
        - app_store_credentials
      vars:
        BUNDLE_ID: "com.mastro.erp"
        APP_STORE_APPLE_ID: "YOUR_APPLE_ID" # Cambia con il tuo
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Build Next.js static
        script: npx next build
      - name: Sync Capacitor iOS
        script: npx cap sync ios
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Build iOS
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xcarchive \
            archive
      - name: Export IPA
        script: |
          cd ios/App
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build/ipa
    artifacts:
      - ios/App/build/ipa/*.ipa
    publishing:
      app_store_connect:
        apple_id: $APP_STORE_APPLE_ID
        role: DEVELOPER
        submit_to_testflight: true

  mastro-android:
    name: MASTRO ERP Android
    max_build_duration: 30
    instance_type: linux_x2
    environment:
      node: 18
      java: 17
      vars:
        PACKAGE_NAME: "com.mastro.erp"
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Build Next.js static
        script: npx next build
      - name: Sync Capacitor Android
        script: npx cap sync android
      - name: Build Android AAB
        script: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/bundle/release/*.aab
      - android/app/build/outputs/apk/release/*.apk
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
